id: ACFEAD17F
title: Prayer to the Gurus of the Chöd Lineage
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:12:27.041508
  last_modified_at: 2022-03-01 03:12:27.041510
