id: ACFEAD17F
title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:12:27.043467
  last_modified_at: 2022-03-01 03:12:27.043471
